-- 建库、建表语句
CREATE DATABASE IF NOT EXISTS db1 DEFAULT CHARACTER SET = 'utf8';
USE db1;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
